app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
from . import user

from app.models import User
from flask import redirect, render_template, url_for
from flask_login import login_required
from app import db


@user.route('/')
def index():
    users = User.query.all()  # SELECT * FROM users
    return render_template('index.html', users=users)

@user.route('/user/<int:id>')
@login_required
def unique(id):
    user = User.query.get(id)
    return render_template('user.html', user=user)


@user.route("/user/delete/<int:id>")
def delete(id):
    user = User.query.filter_by(id=id).first()
    db.session.delete(user)
    db.session.commit()
    return redirect(url_for('index'))

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
<!--    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">-->
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Material Dashboard CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/material-dashboard.css')}}">

    {{ bootstrap.load_css() }}

    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css'>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <script id="dataslayerLaunchMonitors">
console.log('** dataslayer: injecting Launch monitors **');
window._satellite = window._satellite || {};
window._satellite._monitors = window._satellite._monitors || [];
window._satellite._monitors.push({
  ruleTriggered: function(e) {
    window.parent.postMessage(
      {
        type: 'dataslayer_launchruletriggered',
        url: window == window.parent ? window.location.href : 'iframe',
        data: JSON.parse(JSON.stringify(e.rule)),
      },
      '*'
    );
  },
  ruleCompleted: function(e) {
    // console.log('** dataslayer: Launch rule completed **', e.rule);
    var rule = JSON.parse(JSON.stringify(e.rule));
    var sendRule = function() {
        if (window.dataslayer) {
            window.parent.postMessage(
                {
                    type: 'dataslayer_launchrulecompleted',
                    url: window == window.parent ? window.location.href : 'iframe',
                    data: rule,
                },
                '*'
            );
            // console.log('** dataslayer: posted rule '+rule+'**');
        } else {
            if (document.readyState === 'complete') {
                // console.log('** dataslayer: giving up on launch **');
                window._dataslayerQueue = window._dataslayerQueue || [];
                window._dataslayerQueue.push({
                  type: 'dataslayer_launchrulecompleted',
                  url: window == window.parent ? window.location.href : 'iframe',
                  data: rule,
                });
                return;
            } else {
                // console.log('** dataslayer: waiting 250ms to repost rule **');
                window.setTimeout(sendRule, 250);
            }
        }
    }
    sendRule();
    if (
      window._satellite &&
      window._satellite._container &&
      window._satellite._container.dataElements
    ) {
      var elementNames = Object.keys(
        window._satellite._container.dataElements
      ).sort(function(a, b) {
        var nameA = a.toUpperCase();
        var nameB = b.toUpperCase();

        if (nameA < nameB) {
          return -1;
        } else if (nameA > nameB) {
          return 1;
        } else {
          return 0;
        }
      });

      let launchElements = {};

      for (var i = 0; i < elementNames.length; i++) {
        var newElement = JSON.parse(
          JSON.stringify(
            window._satellite._container.dataElements[elementNames[i]]
          )
        );

        let cleanValue = window._satellite.getVar(elementNames[i]);
        if (typeof cleanValue === 'function') {
          cleanValue = '(function)';
        } else if (
          typeof cleanValue === 'object' &&
          typeof cleanValue.then === 'function'
        ) {
          cleanValue = '(Promise)';
        }
        launchElements[elementNames[i]] = cleanValue;
        // launchElements.push({
        //   key: elementNames[i],
        //   value: cleanValue,
        //   element: newElement,
        // });
      }
      try {
        window.parent.postMessage(
          {
            type: 'dataslayer_launchdataelements',
            data: 'found',
            url: window == window.parent ? window.location.href : 'iframe',
            elements: launchElements
          },
          '*'
        );
      } catch (e) {
        console.warn(e);
      }

    }
  },
  ruleConditionFailed: function(e) {
    window.parent.postMessage(
      {
        type: 'dataslayer_launchrulefailed',
        url: window == window.parent ? window.location.href : 'iframe',
        data: JSON.parse(JSON.stringify(e.rule)),
      },
      '*'
    );
  },
});
</script>
    <script style="display: none;">var tvt = tvt || {}; tvt.captureVariables = function(a){for(var b=
new Date,c={},d=Object.keys(a||{}),e=0,f;f=d[e];e++)if(a.hasOwnProperty(f)&&"undefined"!=typeof a[f])try{var g=[];c[f]=JSON.stringify(a[f],function(l,t){try{if("function"!==typeof t){if("object"===typeof t&&null!==t){if(t instanceof HTMLElement||t instanceof Node||-1!=g.indexOf(t))return;g.push(t)}return t}}catch(A){}})}catch(l){}a=document.createEvent("CustomEvent");a.initCustomEvent("TvtRetrievedVariablesEvent",!0,!0,{variables:c,date:b});window.dispatchEvent(a)};window.setTimeout(function() {tvt.captureVariables({'dataLayer.hide': (function(a){a=a.split(".");for(var b=window,c=0;c<a.length&&(b=b[a[c]],b);c++);return b})('dataLayer.hide'),'gaData': window['gaData'],'dataLayer': window['dataLayer']})}, 2000);</script>
    <style type="text/css">
@font-face {
  font-weight: 400;
  font-style:  normal;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-Regular.woff2') format('woff2');
}
@font-face {
  font-weight: 400;
  font-style:  italic;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-Italic.woff2') format('woff2');
}

@font-face {
  font-weight: 500;
  font-style:  normal;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-Medium.woff2') format('woff2');
}
@font-face {
  font-weight: 500;
  font-style:  italic;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-MediumItalic.woff2') format('woff2');
}

@font-face {
  font-weight: 700;
  font-style:  normal;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-Bold.woff2') format('woff2');
}
@font-face {
  font-weight: 700;
  font-style:  italic;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-BoldItalic.woff2') format('woff2');
}

@font-face {
  font-weight: 900;
  font-style:  normal;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-Black.woff2') format('woff2');
}
@font-face {
  font-weight: 900;
  font-style:  italic;
  font-family: 'Inter-Loom';

  src: url('https://cdn.loom.com/assets/fonts/inter/Inter-UI-BlackItalic.woff2') format('woff2');
}</style>


    <script src="{{url_for('static', filename='js/Chart.min.js')}}"></script>
    <title>{% block title %}{% endblock %}</title>


</head>
<body>

<div class="wrapper d-flex align-items-stretch">

    {% include 'components/sidebar.html' %}


    <div id="content" class="">
    {% include 'components/nav.html' %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    </div>

</div>


<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>-->
<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>-->
{{bootstrap.load_js()}}


{% block script %}
{% endblock %}

<script src="{{url_for('static', filename='js/main.js')}}" type="text/javascript"></script>
<script src="{{url_for('static', filename='js/jquery.js')}}"></script>
<!--<script src="{{url_for('static', filename='js/test-ajax.js')}}"></script>-->
<script src="{{url_for('static', filename='js/ajax-form.js')}}"></script>


<!--   Core JS Files   -->
<!--  <script src="assets/js/core/jquery.min.js" type="text/javascript"></script>-->
<!--  <script src="assets/js/core/popper.min.js" type="text/javascript"></script>-->
<!--  <script src="assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>-->









</body>
</html>

app/templates/base_bkp_material_design.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
<!--    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">-->
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <!--     Fonts and icons     -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

    <!-- Material Dashboard CSS -->
<!--    <link rel="stylesheet" href="{{url_for('static', filename='css/material-dashboard.css')}}">-->


    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css'>
    {% block styles %}{{ bootstrap.load_css() }}{% endblock %}
    <title>{% block title %}{% endblock %}</title>


</head>
<body>

{% include 'components/nav.html' %}
<div class="container">

    {% block content %}{% endblock %}
</div>


<!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>-->
<!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>-->
{{bootstrap.load_js()}}

{% block script %}


<!--&lt;!&ndash;   Core JS Files   &ndash;&gt;-->
<!--  <script src="assets/js/core/jquery.min.js" type="text/javascript"></script>-->
<!--  <script src="assets/js/core/popper.min.js" type="text/javascript"></script>-->
<!--  <script src="assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>-->

<!--  &lt;!&ndash; Plugin for the Perfect Scrollbar &ndash;&gt;-->
<!--  <script src="assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>-->

<!--  &lt;!&ndash; Plugin for the momentJs  &ndash;&gt;-->
<!--  <script src="assets/js/plugins/moment.min.js"></script>-->

<!--  &lt;!&ndash;  Plugin for Sweet Alert &ndash;&gt;-->
<!--  <script src="assets/js/plugins/sweetalert2.js"></script>-->

<!--  &lt;!&ndash; Forms Validations Plugin &ndash;&gt;-->
<!--  <script src="assets/js/plugins/jquery.validate.min.js"></script>-->

<!--  &lt;!&ndash;  Plugin for the Wizard, full documentation here: https://github.com/VinceG/twitter-bootstrap-wizard &ndash;&gt;-->
<!--  <script src="assets/js/plugins/jquery.bootstrap-wizard.js"></script>-->

<!--  &lt;!&ndash;	Plugin for Select, full documentation here: http://silviomoreto.github.io/bootstrap-select &ndash;&gt;-->
<!--  <script src="assets/js/plugins/bootstrap-selectpicker.js" ></script>-->

<!--  &lt;!&ndash;  Plugin for the DateTimePicker, full documentation here: https://eonasdan.github.io/bootstrap-datetimepicker/ &ndash;&gt;-->
<!--  <script src="assets/js/plugins/bootstrap-datetimepicker.min.js"></script>-->

<!--  &lt;!&ndash;  DataTables.net Plugin, full documentation here: https://datatables.net/    &ndash;&gt;-->
<!--  <script src="assets/js/plugins/jquery.datatables.min.js"></script>-->

<!--  &lt;!&ndash;	Plugin for Tags, full documentation here: https://github.com/bootstrap-tagsinput/bootstrap-tagsinputs  &ndash;&gt;-->
<!--  <script src="assets/js/plugins/bootstrap-tagsinput.js"></script>-->

<!--  &lt;!&ndash; Plugin for Fileupload, full documentation here: http://www.jasny.net/bootstrap/javascript/#fileinput &ndash;&gt;-->
<!--  <script src="assets/js/plugins/jasny-bootstrap.min.js"></script>-->

<!--  &lt;!&ndash;  Full Calendar Plugin, full documentation here: https://github.com/fullcalendar/fullcalendar    &ndash;&gt;-->
<!--  <script src="assets/js/plugins/fullcalendar.min.js"></script>-->

<!--  &lt;!&ndash; Vector Map plugin, full documentation here: http://jvectormap.com/documentation/ &ndash;&gt;-->
<!--  <script src="assets/js/plugins/jquery-jvectormap.js"></script>-->

<!--  &lt;!&ndash;  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ &ndash;&gt;-->
<!--  <script src="assets/js/plugins/nouislider.min.js" ></script>-->

<!--  &lt;!&ndash; Include a polyfill for ES6 Promises (optional) for IE11, UC Browser and Android browser support SweetAlert &ndash;&gt;-->
<!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/core-js/2.4.1/core.js"></script>-->

<!--  &lt;!&ndash; Library for adding dinamically elements &ndash;&gt;-->
<!--  <script src="assets/js/plugins/arrive.min.js"></script>-->

<!--  &lt;!&ndash;  Google Maps Plugin    &ndash;&gt;-->
<!--&lt;!&ndash;  <script  src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>&ndash;&gt;-->

<!--  &lt;!&ndash; Chartist JS &ndash;&gt;-->
<!--  <script src="assets/js/plugins/chartist.min.js"></script>-->

<!--  &lt;!&ndash;  Notifications Plugin    &ndash;&gt;-->
<!--  <script src="assets/js/plugins/bootstrap-notify.js"></script>-->

<!--  &lt;!&ndash; Control Center for Material Dashboard: parallax effects, scripts for the example pages etc &ndash;&gt;-->
<!--  <script src="assets/js/material-dashboard.min.js?v=2.1.2" type="text/javascript"></script>-->


{% endblock %}


</body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Lista de usuários{% endblock %}

{% block content %}

{% include 'components/notification.html' %}


<ul class="list-group list-group-flush">
    {% for user in users%}
    <li class="list-group-item">
        <a href="{{ url_for('user.unique', id=user.id) }}">
<!--            Nome => {{user.name}} - E-mail => {{user.email}}-->
        </a>
    </li>
<!--    <hr>-->
    {% endfor %}
</ul>

{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block title %}Login{% endblock %}

{% block content %}
  {% include 'components/notification.html' %}
  {{render_form(form)}}

  <h4 class="text-center text-muted">
  Não possui uma conta?
    <a href="{{url_for('auth.register')}}"
       class="btn btn-success btn-link">Faça o seu cadastro</a>
  </h4>


{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block title %}Cadastro{% endblock %}

{% block content %}
    {% include 'components/notification.html' %}
    {{render_form(form)}}
{% endblock %}

app/templates/response.html
{% extends 'bootstrap/base.html' %}

{% block content %}

<h1>Daniel</h1>
{% endblock %}

app/templates/user.html
{% extends 'base.html' %}


{% block title %}{{user.name}}{% endblock %}

{% block content %}

<div>
    <a href="{{url_for('user.index')}}">Voltar</a>
    <table class="table table-striped">
        <tbody>
            <tr>
                <td>{{user.id}}</td>
                <td>{{user.name}}</td>
                <td>{{user.email}}</td>
                <td>{{user.profile.photo}}</td>
                <td><a href="{{ url_for('book.user_add_book', id=user.id) }}" class="btn btn-success">Adicionar Livro</a></td>
                <td><a href="{{ url_for('user.delete', id=user.id) }}" class="btn btn-danger">Deletar</a></td>
            </tr>
        </tbody>
    </table>

    <table class="table table-sm">
      <thead>
        <tr class="table-info">
          <th scope="col">#</th>
          <th scope="col">Livro</th>
        </tr>
      </thead>
      <tbody>
      {% for book in user.books %}
        <tr >
          <th scope="row">{{book.id}}</th>
          <td>{{book.name}}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>




</div>




{% endblock %}